server:
  port: 8001

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/link?useUnicode=true&characterEncoding=UTF-8&rewriteBatchedStatements=true&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    hikari:
      connection-test-query: select 1
      connection-timeout: 20000
      idle-timeout: 30000000
      maximum-pool-size: 5
      minimum-idle: 5


  data:
    redis:
      host: 192.168.88.101
      port: 6379
      password: 123456
